services:
  - type: web
    name: chatbot-rag-api
    env: python
    plan: free
    region: ohio
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn backend.api.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
      - key: PINECONE_INDEX_NAME
        value: "rag-fundamentos"
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false

  - type: web
    name: chatbot-rag-front
    env: static
    plan: free
    region: ohio
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
