services:
  - type: web
    name: chatbot-rag-api
    env: docker
    plan: free
    region: ohio
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: PINECONE_INDEX_NAME
        value: "rag-fundamentos"
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false

  - type: web
    name: chatbot-rag-front
    env: static
    plan: free
    region: ohio
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
